### ISSUE TITLE
EPUB output

### ISSUE THREAD

**Issue by gladomat** [antonvladyka/neural_networks_and_deep_learning_pdf#2]
Great job on the book! I was wondering, can you compile an EPUB for this book? This would make very ebook reader friendly. Since it's in latex, it shouldn't be that much of a problem.

**Comment by antonvladyka** [comment]
Main issue here is with formulas. I can successfully compile latex into html + mathjax backend, but it does not work for the following compilation into epub.
Webtex backend (via latex.codecogs) converts formulas into images, but only inline formulas, not block equations.

**Comment by gladomat** [comment]
Oh, I see. That's too bad. Thanks for trying!
Edit: Would you mind adding the HTML to the repo?

**Comment by antonvladyka** [comment]
I am not a regular user of Epub, and only now I noticed that Calibre correctly shows MathML in epub. HTML removed, fixed Epub added.

**Comment by gladomat** [comment]
That's super cool, thanks!
