### ISSUE TITLE
what command builds the pdf?

### ISSUE THREAD

**Issue by marklemay** [antonvladyka/neural_networks_and_deep_learning_pdf#5]
when I run 
```
latexmk book.tex -pdf
```
I get a 
```
! LaTeX Error: File `currfile.sty' not found.
```
error.

**Comment by antonvladyka** [comment]
Hi

Your command looks correct. 

As I see, **currfile** package is within dependencies of **standalone** package.

You may try to install currfile.sty explicitly (I do not know which system you use; it is available in Miktex for Windows).

Another option is not to use **standalone** package at all.
For this you need to remove \usepackage{standalone} in the main file, and remove all preambles in all included files (all chapters)
